openapi: 3.0.2
info:
    title: Kerli pangaAPI
    version: 1.0.0
servers:
    -
        url: 'http://localhost:8080'
        description: Local development server
paths:
    /users:
        summary: User related operations
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/postUsersRequest'
                required: true
            tags:
                - users
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/userObject'
                    description: User has been created
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                Invalid password:
                                    value:
                                        error: Invalid password
                                Invalid name:
                                    value:
                                        error: Invalid name
                                Invalid username:
                                    value:
                                        error: Invalid username
                    description: Bad request
            summary: Registers a new user
    /sessions:
        summary: Logging users in and out
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/postSessionsRequest'
                required: true
            tags:
                - sessions
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/postSessionsResponse'
                    description: Session token has been created
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                    description: Missing username or password
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                    description: User does not exist or Wrong password
            summary: Create new session token for user (login)
        delete:
            tags:
                - sessions
            responses:
                '204':
                    description: Session token has been deleted
                '401':
                    description: Unauthorized
            security:
                -
                    Authorization: []
            summary: Delete session token (log out)
components:
    schemas:
        postUsersRequest:
            title: POST /users request
            description: ''
            required:
                - name
                - username
                - password
            type: object
            properties:
                name:
                    description: Users full name
                    type: string
                username:
                    description: Username
                    type: string
                password:
                    description: Password
                    type: string
            example:
                name: Mari Maasikas
                username: Mari37
                password: mariparool
        postSessionsRequest:
            title: POST /sessions request
            description: ''
            type: object
            properties:
                username:
                    type: string
                password:
                    type: string
            example:
                username: Juku123
                password: minuparool
        postSessionsResponse:
            title: POST /sessions response
            description: Session has been created
            required: []
            type: object
            properties:
                user:
                    type: object
                    properties:
                        _id:
                            type: string
                        name:
                            type: string
                        username:
                            type: string
                        password:
                            type: string
                        sessions:
                            type: array
                            items:
                                type: object
                                properties:
                                    _id:
                                        type: string
                                    token:
                                        type: string
                        __v:
                            format: int32
                            type: integer
        deleteSessionsRequest:
            title: DELETE /sessions request
            description: ''
            type: object
            properties:
                Authorization:
                    type: string
            example:
                Authorization: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcyMmQxZGRhYWRiZDVhYTBkOGNhMjYiLCJpYXQiOjE2MDEzMTgxODZ9.HABqtzBwtnVxnIoI16ZTNpgklX72-dYHALTL2GDHy58
        userObject:
            title: userObject
            description: ''
            type: object
            properties:
                id:
                    description: User´s ID
                    type: string
                name:
                    description: User`s full name
                    type: string
                username:
                    description: Username
                    type: string
                accounts:
                    description: Array of user`s bank accounts
                    type: array
                    items:
                        $ref: '#/components/schemas/accountObject'
            example:
                id: 5f79bab312c4877b900f9a55
                name: Mars
                username: Mari2
                accounts:
                    -
                        name: Main
                        balance: 10000
                        currency: EUR
                        number: ETC0e861235
                        id: 5f79bab412c4877b900f9a56
        accountObject:
            title: accountObject
            description: ''
            type: object
            properties:
                name:
                    description: Account name
                    type: string
                balance:
                    format: int32
                    description: Funds the account holds
                    type: integer
                currency:
                    description: Funds currency
                    type: string
                number:
                    description: Account number
                    type: string
            example:
                name: Main
                balance: 10000
                currency: EUR
                number: ETCed019ead
        errorResponse:
            title: a generic error response
            description: Generic error response
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message
    securitySchemes:
        Authorization:
            scheme: bearer
            type: http
